language: node_js

node_js:
  - "8"

env:
  matrix:
    - TEST_TYPE=ci

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
  - npm install -g codecov

script:
  - |
    if [ "$TEST_TYPE" = ci ]; then
      npm run ci
    fi
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
